deploy_name = "Cloudbreak"

aws_access_key = ""
aws_secret_key = ""
aws_region = "eu-west-1"
aws_availability_zone = "a"
aws_security_cidr = "0.0.0.0/0"
aws_key_name = ""
aws_ssh_key_file = ""
aws_inst_type = "m3.xlarge"